#!/bin/bash
#sudo apt update && sudo apt -y upgrade && sudo apt -y install mc nodejs npm tmux leiningen links lynx gdebi-core ffmpeg git && sudo apt-get clean
#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#sudo gdebi -n google-chrome-stable_current_amd64.deb
#mv google-chrome-stable_current_amd64.deb /tmp/
#/////////////////////////////////////
#fallocate -l 4G  /swap
#mkswap /swap
#swapon /swap
#sudo nano /etc/rc.local
#!/bin/bash
#swapon /swap
#sudo chmod a+x /etc/rc.local
#/////////////////////////////////////
#cd streamer/
#npm install
#--no-sandbox
#tmux

cd streamer/
DATE=$(date +'%d%m%Y-%H:%M%S')
mkdir /tmp/log-$DATE
touch log
mv log /tmp/log-$DATE
mv log.bash /tmp/log-$DATE

while [ true ]
do
  #http://localhost:3000/#/covid rtp://127.0.0.1:1234 /tmp/out0.flv
  node stream.js http://google.com http://eteris.startfm.lt/startfm.mp3 rtmp://a.rtmp.youtube.com/live2/ky35-51x4-szpz-92m7-7bh6 2>&1 | tee log.bash
done
